release = ["-DCMAKE_BUILD_TYPE=Release"]
debug = ["-DCMAKE_BUILD_TYPE=Debug"]
releasenolp = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO"]
debugnolp = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES"]

custom_debug = [
    "-DCMAKE_BUILD_TYPE=Debug",
    "-DDISABLE_PLUGINS_BY_DEFAULT=YES",
    "-DPLUGIN_ACYCLIC_VALUE_ITERATION_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_TOPOLOGICAL_VALUE_ITERATION_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_INTERVAL_ITERATION_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_IDUAL_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_BISIMULATION_BASED_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_AO_SEARCH_ENABLED=TRUE",
    "-DPLUGIN_EXHDFS_ENABLED=TRUE",
    "-DPLUGIN_LRTDP_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_HDFS_SOLVERS_ENABLED=TRUE",

    "-DPLUGIN_TRAP_AWARE_LRTDP_SOLVER_ENABLED=TRUE",

    #"-DPLUGIN_DEADEND_PRUNING_HEURISTIC_ENABLED=TRUE",
    #"-DPLUGIN_BUDGET_PRUNING_HEURISTIC_ENABLED=TRUE",
    #"-DPLUGIN_DETERMINIZATION_HEURISTIC_ENABLED=TRUE",
    "-DPLUGIN_OCCUPATION_MEASURE_HEURISTICS_ENABLED=TRUE",
    "-DPLUGIN_PROBABILISTIC_PDB_HEURISTIC_ENABLED=TRUE",
    "-DPLUGIN_DETERMINISTIC_GENERATOR_ENABLED=TRUE",
    "-DPLUGIN_PROBABILISTIC_HILLCLIMBING_GENERATOR_ENABLED=TRUE",
    "-DPLUGIN_POLICY_CEGAR_GENERATOR_ENABLED=TRUE"
]

custom_release = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DDISABLE_PLUGINS_BY_DEFAULT=YES",
    "-DPLUGIN_ACYCLIC_VALUE_ITERATION_SOLVER_ENABLED=TRUE",
    #"-DPLUGIN_TOPOLOGICAL_VALUE_ITERATION_SOLVER_ENABLED=TRUE",
    #"-DPLUGIN_INTERVAL_ITERATION_SOLVER_ENABLED=TRUE",
    #"-DPLUGIN_IDUAL_SOLVER_ENABLED=TRUE",
    #"-DPLUGIN_BISIMULATION_BASED_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_AO_SEARCH_ENABLED=TRUE",
    #"-DPLUGIN_EXHDFS_ENABLED=TRUE",
    "-DPLUGIN_LRTDP_SOLVER_ENABLED=TRUE",
    "-DPLUGIN_HDFS_SOLVERS_ENABLED=TRUE",

    #"-DPLUGIN_DEADEND_PRUNING_HEURISTIC_ENABLED=TRUE",
    #"-DPLUGIN_BUDGET_PRUNING_HEURISTIC_ENABLED=TRUE",
    #"-DPLUGIN_DETERMINIZATION_HEURISTIC_ENABLED=TRUE",
    "-DPLUGIN_OCCUPATION_MEASURE_HEURISTICS_ENABLED=TRUE",
    "-DPLUGIN_PROBABILISTIC_PDB_HEURISTIC_ENABLED=TRUE",
    "-DPLUGIN_DETERMINISTIC_GENERATOR_ENABLED=TRUE",
    "-DPLUGIN_PROBABILISTIC_HILLCLIMBING_GENERATOR_ENABLED=TRUE",
    "-DPLUGIN_POLICY_CEGAR_GENERATOR_ENABLED=TRUE"
]

DEFAULT = "minimal"
DEBUG = "debug"
