#include "downward_cli/open_lists/open_list_options.h"

#include "language/plugins/plugin.h"

using namespace std;

namespace downward::cli {

void add_open_list_options_to_feature(language::plugins::Feature& feature)
{
    feature.add_option<bool>(
        "pref_only",
        "insert only nodes generated by preferred operators",
        "false");
}

tuple<bool> get_open_list_arguments_from_options(
    const language::Context& context,
    const language::plugins::Options& opts)
{
    return make_tuple(opts.get<bool>(context, "pref_only"));
}

} // namespace downward::cli