#include "downward_plugins/open_list_options.h"

#include "downward_plugins/plugins/plugin.h"

using namespace std;

namespace downward_plugins {

void add_open_list_options_to_feature(plugins::Feature& feature)
{
    feature.add_option<bool>(
        "pref_only",
        "insert only nodes generated by preferred operators",
        "false");
}

tuple<bool> get_open_list_arguments_from_options(const plugins::Options& opts)
{
    return make_tuple(opts.get<bool>("pref_only"));
}

} // namespace downward_plugins