#include "standard_scalar_open_list.h"
#include "open_list_factory.h"

#include "../evaluator.h"
#include "../option_parser.h"
#include "../plugin.h"
#include "../state_id.h"

#include <cassert>

using namespace std;

/*
  Open list indexed by a single int, using FIFO tie-breaking.
  Implemented as a map from int to deques.
*/

template<class Entry>
StandardScalarOpenList<Entry>::StandardScalarOpenList(const options::Options &opts)
    : OpenList<Entry>(opts.get<bool>("pref_only")),
      size(0),
      evaluator(opts.get<std::shared_ptr<Evaluator> >("eval")) {
}

template<class Entry>
StandardScalarOpenList<Entry>::StandardScalarOpenList(
    std::shared_ptr<Evaluator> eval, bool preferred_only)
    : OpenList<Entry>(preferred_only), size(0), evaluator(eval) {
}


template<class Entry>
StandardScalarOpenList<Entry>::~StandardScalarOpenList() {
}

template<class Entry>
int StandardScalarOpenList<Entry>::insert(const Entry &entry) {
    if (OpenList<Entry>::only_preferred && !last_preferred)
        return 0;
    if (dead_end)
        return 0;
    int key = last_evaluated_value;
    buckets[key].push_back(entry);
    ++size;
    return 1;
}

template<class Entry>
Entry StandardScalarOpenList<Entry>::remove_min(vector<int> *key) {
    assert(size > 0);
    typename std::map<int, Bucket>::iterator it;
    it = buckets.begin();
    assert(it != buckets.end());
    if (key) {
        assert(key->empty());
        key->push_back(it->first);
    }
    assert(!it->second.empty());
    Entry result = it->second.front();
    it->second.pop_front();
    if (it->second.empty())
        buckets.erase(it);
    --size;
    return result;
}


template<class Entry>
bool StandardScalarOpenList<Entry>::empty() const {
    return size == 0;
}

template<class Entry>
void StandardScalarOpenList<Entry>::clear() {
    buckets.clear();
    size = 0;
}

template<class Entry>
void StandardScalarOpenList<Entry>::evaluate(int g, bool preferred) {
    get_evaluator()->evaluate(g, preferred);
    last_evaluated_value = get_evaluator()->get_value();
    last_preferred = preferred;
    dead_end = get_evaluator()->is_dead_end();
    dead_end_reliable = get_evaluator()->dead_end_is_reliable();
}

template<class Entry>
bool StandardScalarOpenList<Entry>::is_dead_end() const {
    return dead_end;
}

template<class Entry>
bool StandardScalarOpenList<Entry>::dead_end_is_reliable() const {
    return dead_end_reliable;
}

template<class Entry>
void StandardScalarOpenList<Entry>::get_involved_heuristics(
    std::set<Heuristic *> &hset) {
    evaluator->get_involved_heuristics(hset);
}

INSTANTIATE_OPEN_LIST(StandardScalarOpenList)

StandardScalarOpenListFactory::StandardScalarOpenListFactory(
        std::shared_ptr<Evaluator> eval,
                        bool preferred_only)
    : FallthroughOpenListFactory(Options())
{
    opts.set<std::shared_ptr<Evaluator> >("eval", eval);
    opts.set<bool>("pref_only", preferred_only);
}

static std::shared_ptr<OpenListFactory> _parse(options::OptionParser &parser) {
    parser.document_synopsis(
        "Standard open list",
        "Standard open list that uses a single evaluator");
    parser.add_option<std::shared_ptr<Evaluator> >("eval", "scalar evaluator");
    parser.add_option<bool>(
        "pref_only",
        "insert only nodes generated by preferred operators", "false");
    options::Options opts = parser.parse();

    if (parser.dry_run())
        return 0;
    else
        return std::make_shared<StandardScalarOpenListFactory>(opts);
}

static Plugin<OpenListFactory> _plugin("single", _parse);
